//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Fihirana_database.fihirana
{

    public partial class Category : XPLiteObject
    {
        long fID_category;
        [Key]
        public long ID_category
        {
            get { return fID_category; }
            set { SetPropertyValue<long>(nameof(ID_category), ref fID_category, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        decimal fField;
        [Indexed(Name = @"iField_Category")]
        public decimal Field
        {
            get { return fField; }
            set { SetPropertyValue<decimal>(nameof(Field), ref fField, value); }
        }
    }

}
