//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Fihirana_database.fihirana
{

    [Indices(@"Hymnals", "Categories")]
    public partial class HymnalHymnals_CategoryCategories : XPLiteObject
    {
        decimal fCategories;
        [Indexed(@"Hymnals", Name = @"iCategoriesHymnals_HymnalHymnals_CategoryCategories", Unique = true)]
        public decimal Categories
        {
            get { return fCategories; }
            set { SetPropertyValue<decimal>(nameof(Categories), ref fCategories, value); }
        }
        decimal fHymnals;
        public decimal Hymnals
        {
            get { return fHymnals; }
            set { SetPropertyValue<decimal>(nameof(Hymnals), ref fHymnals, value); }
        }
        long fOID;
        [Key]
        public long OID
        {
            get { return fOID; }
            set { SetPropertyValue<long>(nameof(OID), ref fOID, value); }
        }
        long fOptimisticLockField;
        public long OptimisticLockField
        {
            get { return fOptimisticLockField; }
            set { SetPropertyValue<long>(nameof(OptimisticLockField), ref fOptimisticLockField, value); }
        }
    }

}
