// ------------------------------------------------------------
// Author: Rindra Razafinjatovo
// Created on: 2018
// Last Modified: Dec 2024
// Project: Tahiry
// Description: A collection of Bible and Hymnals to streamline and enhance worship presentations for churches.
// ------------------------------------------------------------

﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Fihirana_database.fihirana
{

    public partial class Settings : XPLiteObject
    {
        long fId;
        [Key]
        public long ID
        {
            get { return fId; }
            set { SetPropertyValue<long>(nameof(ID), ref fId, value); }
        }
       
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof( Description ), ref fDescription, value); }
        }

        string fValue;
        public string Value
        {
            get { return fValue; }
            set { SetPropertyValue<string>( nameof( Value ), ref fValue, value ); }
        }

    }

}
