//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fihirana_database.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fihirana_database.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap adventist_symbol__white {
            get {
                object obj = ResourceManager.GetObject("adventist_symbol__white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @charset &quot;UTF-8&quot;;/*!
        /// * animate.css - https://animate.style/
        /// * Version - 4.1.1
        /// * Licensed under the MIT license - http://opensource.org/licenses/MIT
        /// *
        /// * Copyright (c) 2020 Animate.css
        /// */:root{--animate-duration:1s;--animate-delay:1s;--animate-repeat:1}.animate__animated{-webkit-animation-duration:1s;animation-duration:1s;-webkit-animation-duration:var(--animate-duration);animation-duration:var(--animate-duration);-webkit-animation-fill-mode:both;animation-fill-mode:both}.animate__animated.animate__infi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string animate_min_css {
            get {
                return ResourceManager.GetString("animate_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to const element = document.querySelector(&apos;.grid&apos;);
        ///
        ///
        /////Fonction de lancement
        ///$(&apos;.grid&apos;).ready(function () {
        ///    const currentImage = localStorage.getItem(&apos;image&apos;);
        ///    const currentFont = localStorage.getItem(&apos;font&apos;);
        ///    const currentAlignment = localStorage.getItem(&apos;alignment&apos;);
        ///    const currentVideo = localStorage.getItem(&apos;video&apos;);
        ///    const currentColor = localStorage.getItem(&apos;color&apos;);
        ///
        ///    $(&apos;.image-container&apos;).css(&apos;background-image&apos;, &apos;url(&quot;&apos; + currentImage + &apos;&quot;)&apos;);
        ///    $(&apos;#parent&apos;).css(&quot;fon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string app {
            get {
                return ResourceManager.GetString("app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  $(document).ready(() =&gt; {
        ///     $(&apos;.grid&apos;).hide();
        /// });
        /// //Fonction pour changer la parole
        /// function _BibleVerse(text, verse, animation) {
        ///     $(&apos;.grid&apos;).show();
        ///     $(&apos;.bible&apos;).html(text);            
        ///     animateCSS(&apos;.grid&apos;, animation);
        ///     textFit($(&apos;.grid&apos;));
        ///     $(&apos;.verse&apos;).html(verse);
        /// }       
        ///
        /// //Fonction pour animer le texte en injectant les mots-clés
        /// const animateCSS = (element, animation, prefix = &apos;animate__&apos;) =&gt;
        ///   
        ///     new Promise((resolve, reject) =&gt; {
        ///         const ani [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string app_bible {
            get {
                return ResourceManager.GetString("app_bible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage black_screen_2205227 {
            get {
                object obj = ResourceManager.GetObject("black_screen_2205227", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage book_pile_icon_by_Vexels {
            get {
                object obj = ResourceManager.GetObject("book-pile-icon-by-Vexels", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage expand_1886921 {
            get {
                object obj = ResourceManager.GetObject("expand_1886921", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage iconfinder_devices_projector_1287538 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_devices_projector_1287538", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage iconfinder_free_27_616650 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_free-27_616650", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage iconfinder_free_38_974778 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_free-38_974778", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage iconfinder_icon_136_document_edit_314251 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_icon-136-document-edit_314251", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage iconfinder_Info_Circle_Symbol_Information_Letter_1396823 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_Info_Circle_Symbol_Information_Letter_1396823", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage iconfinder_Itunes_1026476 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_Itunes_1026476", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage iconfinder_Movie_play_video_you_tube_youtube_271505 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_Movie_play_video_you_tube_youtube_271505", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage iconfinder_simpline_53_2305609 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_simpline_53_2305609", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage iconfinder_slice399_2859058 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_slice399_2859058", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage iconfinder_view_refresh_118801 {
            get {
                object obj = ResourceManager.GetObject("iconfinder_view-refresh_118801", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;css/animate.min.css&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;css/style.css&quot; /&gt;
        ///    &lt;title&gt;Projection Fihirana&lt;/title&gt;
        ///    &lt;style&gt;
        ///        .grid {
        ///            -webkit-transition: all 0.5s ease;
        ///            -moz-transition: all 0.5s ease;
        ///            -o-transition: all 0.5s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Verset biblique&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;blockquote class=&quot;quote grid animate__animated&quot;&gt;
        ///        &lt;p class=&quot;bible&quot;&gt;&lt;/p&gt;
        ///        &lt;cite class=&quot;verse&quot;&gt;&lt;/cite&gt;
        ///    &lt;/blockquote&gt;
        ///
        ///&lt;/body&gt;
        ///
        ///&lt;/html&gt;.
        /// </summary>
        internal static string index_bible_html {
            get {
                return ResourceManager.GetString("index_bible_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.11.1 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=c.slice,e=c.concat,f=c.push,g=c.indexOf,h={},i=h.toString,j=h.hasOwnProperty,k={},l=&quot;1.11.1&quot;,m=function(a,b){return new m.fn.init(a,b)},n=/^[\s\uFEFF\xA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_min_js {
            get {
                return ResourceManager.GetString("jquery_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage logo_propre_381399 {
            get {
                object obj = ResourceManager.GetObject("logo_propre_381399", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage note_book_flat_icon_by_Vexels {
            get {
                object obj = ResourceManager.GetObject("note-book-flat-icon-by-Vexels", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage notebook_school_icon_by_Vexels {
            get {
                object obj = ResourceManager.GetObject("notebook-school-icon-by-Vexels", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Play_content_1495055 {
            get {
                object obj = ResourceManager.GetObject("Play_content_1495055", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Presentation_4470693 {
            get {
                object obj = ResourceManager.GetObject("Presentation_4470693", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage projection_svgrepo_com {
            get {
                object obj = ResourceManager.GetObject("projection-svgrepo-com", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*RINDRA RAZAFINJATOVO*/
        ///html {
        ///    font-size: clamp(60px, 6vw, 120px);
        ///}
        ///
        ///body {
        ///    overflow: hidden;
        ///}
        ///
        ///.grid {
        ///    position: relative;    
        ///    width: 100%;
        ///    height: 90vh;
        ///    display: flex;
        ///    align-items: center;
        ///    justify-content: center;
        ///    text-shadow: 2px 3px 5px rgba(0,0,0,0.5), 
        ///        0px 8px 13px rgba(0,0,0,0.1), 
        ///        0px 18px 23px rgba(0,0,0,0.1);    
        ///    line-height: 1;
        ///    top: 10px;
        ///}
        ///
        ///.lyrics {
        ///    color: white;
        ///    animation-duration: 1s;
        ///}
        ///
        ///#parent [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body::before {
        ///    content: &quot;Bible&quot;;
        ///    font-size: 130vh;
        ///    color: rgba(0, 0, 0, 0.1);
        ///    position: absolute;
        ///    top: -35vh;
        /// }
        ///
        ///body {
        ///    height: 100vh;
        ///    overflow: hidden;
        ///    background-image: radial-gradient( farthest-corner at 40px 40px, rgba(33, 29, 28, 0.7) 0%, rgb(77, 77, 77) 100% );
        ///    /*background-image: url(&quot;bg.jpeg&quot;);*/
        ///    display: flex;
        ///    align-items: center;
        ///    justify-content: center;
        ///    object-fit: contain;
        ///}
        ///
        ///blockquote {
        ///    color: white;
        ///    font-family: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string style_bible_css {
            get {
                return ResourceManager.GetString("style_bible_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(root,factory){&quot;use strict&quot;;if(typeof define===&quot;function&quot;&amp;&amp;define.amd){define([],factory)}else if(typeof exports===&quot;object&quot;){module.exports=factory()}else{root.textFit=factory()}})(typeof global===&quot;object&quot;?global:this,function(){&quot;use strict&quot;;var defaultSettings={alignVert:false,alignHoriz:false,multiLine:false,detectMultiLine:true,minFontSize:6,maxFontSize:80,reProcess:true,widthOnly:false,alignVertWithFlexbox:false};return function textFit(els,options){if(!options)options={};var settings={};for(va [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textFit_min_js {
            get {
                return ResourceManager.GetString("textFit_min_js", resourceCulture);
            }
        }
    }
}
